### ISSUE TITLE
Feature Suggestion: Detect malware

### ISSUE THREAD

**Issue by Fernfrost** [quidsup/notrack#122]
Use a malware list to block calls/posts from malware. Can then identify the device that possibly is infected and needs attention.

**Comment by quidsup** [comment]
I've been thinking how best to do this when considering the lack of power from ARM devices means it couldn't really be a constant running job.
Perhaps an overnight Cron job using the dns-log-archive.sh, which could write the result of any detections found into file which would then be read by index.php?

**Comment by fernfrost** [comment]
Your absolutely right. The notification does not need to be instant so a cron job would do the trick. The request itself would be blocked anyhow?

**Comment by Quacky2200** [comment]
If this is possible, it would be a nice feature request where you could attach an email onto the hosts that go through NoTrack. If it detects malware or someone accesses something that's blocked, you could optionally mail them using an example like so:
 
'You passed through this host which is known to be deceitful/malicious, you should check your device for any suspicious activity through an antivirus/anti-malware program.' 

'You have tried to access a blocked website/domain, if you wish to view this content and you think it has been blocked on accident, please contact us at [email]'.

Of course you'd need to have a type of user notifying block system so that it doesn't spam you with emails from adverts being blocked or something...Also a host and email system to know who's who

I thought this would be a nice feature request for libraries/colleges/schools etc where someone may sign up their device to the network and could notify them automatically and allow them to opt-out of the emails.  Not as though it is **that** necessary though, any thoughts perhaps?

**Comment by quidsup** [comment]
Feature added in e73183907975fb29077e0c541a5a6257f67bf14d
