### ISSUE TITLE
IDEA: option to whitelist

### ISSUE THREAD

**Issue by Xmetalfanx** [quidsup/notrack#14]
Remembering that I do not know "how the lists" are setup on the backend, I would think that on the main page about where the "whois" and "search" buttons are, maybe put a button (somewhere around there anyway) to whitelist/add to exceptions option... though i would also think there may be an "exceptions" page somewhere in the configurations in order to UN-whitelist an item if you want to. 

I thought of "a checkbox" option for "exceptions" on the blocklist page....  but that would clutter up the blocklist page for something that you only want to do (add to a white-list) every so often .... IF EVER.

**Comment by quidsup** [comment]
Its an imminent change planned for version 0.7.
My plan was to add a checkbox next to each site on the Blocklist page, under Config.

In Future that table will have Site name, Ad company, and a checkbox.

Most of the work is done on the backend. All thats needed is the necessary Javascript and PHP adjustments to the frontend.

A checkbox on the Stats page is an idea, but I'm concerned that its prone to false positives.
Its more an issue with processing power, rather than issue of can't be programmed.
