### ISSUE TITLE
Preferences not saving 

### ISSUE THREAD

**Issue by jdyx** [quidsup/notrack#16]
On 0.6.1, when I select 'Blocked by Notrack' on the config page, then return to the config page the radio button still says 1x1, is it saved? Also when attempting to add new block lists I get 
"Copying /tmp/notrack.conf to /etc/notrack.conf
Updating Blocklists..." But it just sits there, and if I return to the config page none of the block list radio buttons are checked and the tracker no. remains the same. Is it a case of waiting for a longer period?

**Comment by jdyx** [comment]
A full re-install seems to have fixed it.

**Comment by quidsup** [comment]
I was experimenting a bit with the block list save page. At the moment the web page forks a new process to update the block lists. Worse case on a RPi 2 I was clocking in at 5 minutes, so to delay a web page loading will cause the browser to take corrective action.
It is an issue because I'm not giving clear direction.

I should really have it go straight back to the config page
