### ISSUE TITLE
After midnight , domains are wrong in DNS stats page

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#169]
As in the title, it can be seen in the screenie bellow that the first 8 are from 23:58 , while all other are util around 01:52 , around my correct time.
I've experience this almost every day when checking that page around this time.

![image](https://cloud.githubusercontent.com/assets/10121067/20026853/63eb1ede-a2fb-11e6-8251-2109331f7e19.png)

**Comment by quidsup** [comment]
Is this fixed now?
I can't stay up past midnight to check it now with the hours I have to work

**Comment by duramato** [comment]
It isn't, happens always. If you wake up super early like 6am try seeing if it still happens at that time.

**Comment by quidsup** [comment]
Looking at the historic view it's correct for me. I have 01:00 am, 00:00, and 23:00 in order

**Comment by duramato** [comment]
It's the by time view

**Comment by quidsup** [comment]
They share the same query, thats why I'm confused if it works for historic view it should also work for live view
```
$query = 'SELECT * FROM live'.add_filterstr(). ' **ORDER BY UNIX_TIMESTAMP(log_time)** '.$sort.' LIMIT '.ROWSPERPAGE.' OFFSET '.(($page-1) * ROWSPERPAGE);
$query = 'SELECT * FROM historic'.add_filterstr().add_datestr(). ' **ORDER BY UNIX_TIMESTAMP(log_time)** '.$sort.' LIMIT '.ROWSPERPAGE.' OFFSET '.(($page-1) * ROWSPERPAGE);

```

**Comment by duramato** [comment]
Just now:

![image](https://lol.doyou.bid/wL1JD.png)

**Comment by quidsup** [comment]
I finally managed to stay up past midnight and saw the issue.

I have just realised what it is:
The date doesn't appear in the dnsmasq log file, so I take it from the system time when ntrk-parse is run.

say the date is 24 Nov and ntrk-parse runs at 23:55

In date/time in full the SQL table would be:
2016-11-24 23:55:00 site.com
2016-11-24 23:54:00 site.com
2016-11-24 23:53:00 site.com
etc...

The next run of ntrk-parse runs at 00:05 and records the date as 25 Nov
The SQL table would now be:
2016-11-25 23:59:00 anothersite.com
2016-11-25 23:58:00 anothersite.com
2016-11-25 23:57:00 anothersite.com
2016-11-25 00:04:00 anothersite.com
2016-11-25 00:03:00 anothersite.com
2016-11-25 00:02:00 anothersite.com
2016-11-24 23:55:00 site.com
2016-11-24 23:54:00 site.com
2016-11-24 23:53:00 site.com

By the time the data is added to historic table there is more around and the order appears correct

How to program around that in bash?
Month and Day appear in the log file, so those could be used instead of system date value.
Year would have to be taken from the current system time.

But I can guess what happens on 31 Dec 2016 if ntrk-parse runs at 23:55, and then the next run is on 01 Jan 2017 at 00:05.
The data between 23:56 and 23:59:59 is going to be recorded on the wrong year.

**Comment by quidsup** [comment]
Possible fix
```
#Constants
DATENOW="$(date +"%Y-%m-%d")"
DATEYESTERDAY=date -d @$(( $(date +"%s") - 86400)) +"%Y-%m-%d"
CURRENTDAY="$(date +"%d")"

function process_todaylog() {
  local dedup_answer=""
  local line=""
  local -A querylist
  local -A systemlist
  local url=""
  local dns_result=""  

  echo "Processing log file"
    
  for line in "${logarray[@]}"; do
    if [[ $line =~ ^[A-Z][a-z][a-z][[:space:]][[:space:]]?([0-9]{1,2})[[:space:]]([0-9]{2}\:[0-9]{2}\:[0-9]{2})[[:space:]]dnsmasq\[[0-9]{1,6}\]\:[[:space:]](query|reply|config|\/etc\/localhosts\.list)(\[[A]{1,4}\])?[[:space:]]([A-Za-z0-9\.\-]+)[[:space:]](is|to|from)[[:space:]](.*)$ ]]; then
      url="${BASH_REMATCH[5]}"
      
      if [[ ${BASH_REMATCH[3]} == "query" ]]; then
        if [[ ${BASH_REMATCH[4]} == "[A]" ]]; then         #Only IPv4 (prevent double)
          if [[ ${BASH_REMATCH[1]} == $CURRENTDAY ]]; then  #Fix for dealing with date transition
            querylist[$url]="$DATENOW ${BASH_REMATCH[2]}"             #Add datetime to query array
          else
            querylist[$url]="$DATEYESTERDAY ${BASH_REMATCH[2]}"             #Add datetime to query array
          fi
          systemlist[$url]="${BASH_REMATCH[7]}"            #Add IP to system array
        fi      
      elif [[ $url != "$dedup_answer" ]]; then   #Simplify processing of multiple IP addresses returned
        dedup_answer="$url"                      #Deduplicate answer
        if [ "${querylist[$url]}" ]; then        #Does answer match a query?
          if [[ ${BASH_REMATCH[3]} == "reply" ]]; then dns_result="A"    #Allowed
          elif [[ ${BASH_REMATCH[3]} == "config" ]]; then dns_result="B" #Blocked
          elif [[ ${BASH_REMATCH[3]} == "/etc/localhosts.list" ]]; then dns_result="L"
          fi
          
          simplify_url "$url"                    #Simplify with commonsites
          
          if [[ $simpleurl != "" ]]; then        #Add row into SQL Table
            echo "INSERT INTO live (id,log_time,sys,dns_request,dns_result) VALUES ('null','${querylist[$url]}', '${systemlist[$url]}', '$simpleurl', '$dns_result')" | mysql --user="$USER" --password="$PASSWORD" -D "$DBNAME"
          fi
                    
          unset querylist[$url]                  #Delete value from querylist
          unset systemlist[$url]                 #Delete value from system list
        fi      
      fi
    fi
  done
  unset IFS  
}
```
