### ISSUE TITLE
Element Remover

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#186]
I see a lot of [this](https://gyazo.com/2e06a82a85ddeb0677303f89cc214227) and I was wondering if there was a Add on or User script that could block no-track blocked elements, I know using a browser ad-block will do it as well, but then its blocking them and not No-Track.

**Comment by Serkan-devel** [comment]
ublock origin maybe?

**Comment by ShayBox** [comment]
Well like i said, using a ad-blocker like normally would block the elements, but will do it locally, and not let no-track do it, so its using my pc's resources and not showing on notrack's statistics

**Comment by quidsup** [comment]
The problem is HTTPS adverts and lack of valid certificate to cover all domains.
Its not really something that can be solved without undermining the overall security of HTTPS on your system.

I use ublock origin in advanced user mode with all the 3rd party blocklists disabled. I'm just making use of the element hider to block abusive ads that are self-hosted, e.g. Amazon and eBay.
My ublock blocklist is only a few lines long, so that takes minimal resources, and allows NoTrack to do the majority of blockling.

**Comment by Quacky2200** [comment]
I'm not sure how this would exactly work, but could you somehow simply just send back a redirect request towards another domain so that it could display an invisible page/image etc. I dunno how effective it would be and how worth the work would be, could be interesting to look up upon though?
