### ISSUE TITLE
Incorrect version number displayed when upgrading

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#21]
This has happened every time a 0.X.1 version comes out http://prntscr.com/a7hwis the home page and this page will show a new update, but its the version that came before it. the update command wont downgrade, so its not a big issue, but it just displays it wrongly

**Comment by quidsup** [comment]
It will sort itself out in a couple of days.

I suspect the problem is the latest version information is handled by notrack.sh tracker updating. Recently I've been reducing the frequency of updates, so the version will be displayed wrong if you upgrade prior to being informed.

But yes I take your point that it is a bug.

**Comment by quidsup** [comment]
Fix applied
