### ISSUE TITLE
[Discussion] Man in the middle attack on No Track users

### ISSUE THREAD

**Issue by mattpalermo** [quidsup/notrack#210]
As I have seen discussed before, it doesn't seem possible to forge valid, properly signed SSL certificates for the blocked domains (for good reasons). This means that blocked requests either have to go through HTTP or HTTPS with a SSL cert which is not validated.

If an attacker owned any part of the network between the user and the No Track server, it seems to me that it would be possible for the attacker to return their own responses back to the user instead of the blank, innocent, 1x1 pixels. For HTTP sites, I think this is already possible which is why the user knows not to do anything sensitive on a HTTP site. But for sites which are HTTPS, this seems like an attacker could gain more control over the no track user's browser than would be otherwise possible without no track.

I am no expert in this topic so I am not sure if "cross-site" browser security would prevent this type of attack from causing any harm, or if there are any other flaws in my thinking. I would love to hear from anyone that could help evaluate the validity of this vulnerability. Constructing a demonstration / test of this attack is beyond my capabilities.

Just to be clear, this will not be of concern to anyone who controls the network between themselves and their No Track server (which I am assuming to be most users).

**Comment by quidsup** [comment]
The data being exchanged between the browser and NoTrack server is going to be one of three items:

1. HTTP GET Request to download the sink page (1x1 pixel or message)
2. HTTP POST Request sending tracking data 
3. Admin page

Items 1 and 2 are caused by redirecting of DNS request, and as previously pointed out it is impossible / impracticable to have a valid certificate with correct signing chain.
Perhaps out of the two points there it is Point 2 which could cause data to be leaked away. I have observed Ghostery blindly accept the SSL certificate and send tracking data.
Windows 10 is smarter and won't accept the SSL certificate.
But thats just two examples.
You could potentially loose tracking data to an attacker that you didn't know would be sent to another company.

As to gaining control over the browser...
A man-in-the-middle attack could target the non-encrypted HTTP connection and serve up a different sinkhole page just as easy as the HTTPS connection. So lets count that as well.
There are plenty of examples of exploit kits to take over a browser, so yes its a potential attack.

Most exploit kits generally target Flash player or Java.
If you don't have Flash or Java, then it effectively neutralises that attack vector.

But there has to be a vulnerability somewhere to allow an attacker to gain a toehold in a network.
Even if NoTrack was exposed to an Internet connection, I am fairly confident that there is sufficient protection on the user input fields to prevent any kind of attack against the webserver or SQL database.
**I'm all for anyone carrying out an audit to make sure I haven't missed anything.**

If the user has left SSH port open and poorly protected, then that is a very real attack vector.

**Comment by mattpalermo** [comment]
Thankyou for your thoughts on this @quidsup.

You raise a good point about HTTP POST that I didn't consider.

As for HTTP GET:
> Most exploit kits generally target Flash player or Java.
If you don't have Flash or Java, then it effectively neutralises that attack vector.

I was actually just considering something far less technical. Being able to simply inject some HTML, CSS or JS into a page could be quite dangerous itself (e.g. Phishing). Do you think this is valid?

> But there has to be a vulnerability somewhere to allow an attacker to gain a toehold in a network.

I have plenty of control over the only route between my household LAN and the internet. One day I may turn evil against innocent house guests who use an internet accessible No Track... Mwhahaha! (please read this with humor implied).

> Even if NoTrack was exposed to an Internet connection, I am fairly confident that there is sufficient protection on the user input fields to prevent any kind of attack against the webserver or SQL database.

Are you now talking about the NoTrack admin interface and server itself? I don't have any concerns about this. I'm sure you did a good job at this :) :+1: 

> If the user has left SSH port open and poorly protected, then that is a very real attack vector.

Clearly. Although this is an implementation issue that's not fundamental to NoTrack.

Based upon the discussion so far I am going to discontinue the Public No Track server I had running (My VPS provider has also asked me to disable my public recursive dns server, so it will have to happen anyway). Subject to any conclusions drawn from further discussion, perhaps a warning could be added somewhere like the README page suggesting that using NoTrack in a similar set up to my Public No Track demonstration may not be secure. What do you think?
