### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#23]
I've noticed the new ui improvements, pictures and graphics, nice work.

Also, when changing some things in the menu, it outputs the log on the page, when it has to update scripts and goes through 1-100% it fills the page, maybe make the log expandable or something, just an idea so it doesnt fill the page https://i.imgur.com/cjW3m3F.png

Another thing, at the end of the same log it said this https://i.imgur.com/ZwE9847.png probbably because of my wifi-hotspot, and it seems to not break anything, dnsmasq is still working and the hotspot works find, so maybe just random, though i'd let you know if you understand it.

And last thing, i know its alot, but the Blocklist seems to be laggy again, it used to be but you fixed it in 0.6.1, now its back, you may already know about this one, maybe make some sort of page and have each page max of 50 or something entries, like the google results page. cause when i load that page it makes my server's cpu go to 100% cpu (although i have a bad pc Single core 2.20ghz cpu)

**Comment by quidsup** [comment]
Thanks

That config.php page is going to be next on my list, I want to move away from the log style output to a simpler popup like when you hit Pause button.

I agree pagination is in dire need now on the Blocklist since I moved it to a table format. 100K plus rows (if you have all the blocklists enabled) is too much even for my RPi2 server and old 3.3Ghz hex core pc.
