### ISSUE TITLE
Auto renew IP 

### ISSUE THREAD

**Issue by macca1** [quidsup/notrack#43]
I noticed that after the 24h time has expired, the device is removed from DHCP leases page. I assume that this means the device is no longer on no track. 

My iPhone still has the DNS in as no track is, but is not showing after 24hr. If I reboot the phone, it shows up again for another 24 hours. 

To auto renew this would be good, instead of dropping off the system.

**Comment by quidsup** [comment]
NoTrack is reading the Lease log file from Dnsmasq.
You can change the lease time in /etc/dnsmasq.conf
Look for the line that says something like: dhcp-range=192.168.0.50,192.168.0.150,12h

I haven't tried, but maybe you can set it to 7d, instead of 12h? 

Its up to the device to re-request an IP when the lease is up. If it doesn't receive a response from Dnsmasq DHCP server, then it must cease network activity.
