### ISSUE TITLE
Blocking Local IP, not whitelisting

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#46]
It seems that i changed the port for Lighttpd because my NAS uses 80 for apache2, worked fine, but it tries to block that port when i visit the admin page, it doesn't work but said it in the blocked pages http://prntscr.com/be7cyh so...? nothing's broken that i can tell but it is saying its being blocked

**Comment by ShayBox** [comment]
It seems it is affecting Multicraft, it cant communicate to the backend for the webui... even after i tried adding the local ip to the whitelist, whitelist doesnt apply instantly, it takes a few hours, and pausing doesn't work at all

**Comment by quidsup** [comment]
Its just aesthetics that the root web folder will show up in the list. NoTrack block image / message was shown, and thats what I'm looking for in the lighttpd log file.

For my system the log entry occured when I manually typed in: notrack.local
without specifying /admin

I couldn't think how to negate that in PHP without knowing the system name / IP address, since everyones system can be setup differently.

**Comment by ShayBox** [comment]
Seems to be fixed after i uninstalled/reinstalled... wierd but its gone now

**Comment by ShayBox** [comment]
Tried putting multicraft / ownCloud in the lighttpd directory, but it actually blocks them. not aesthetic anymore, but not a big problem, i moved them out
