### ISSUE TITLE
New webui using angular and bootstrap 

### ISSUE THREAD

**Issue by mariogrip** [quidsup/notrack#6]
Hi,

I made a quck little "preview" of a new webui that uses angular: https://github.com/mariogrip/notrack/tree/master/admin/new

I made an API in php that just servers out json. Javascript then handles the rest on client side, this way I take the load away from the server. Using javascript we can make dynamic webpages. I made a quick search function with javascript and angular to show just how dynamic and flexible it is.

note: this was made as an "preview" so there is much copy paste!
 
![img3](https://cloud.githubusercontent.com/assets/1642635/12534394/c9f59ebe-c257-11e5-9357-cacc4e7005d2.png)
![img2](https://cloud.githubusercontent.com/assets/1642635/12534395/cb3922a0-c257-11e5-9033-868d544d8ff5.png)
![img1](https://cloud.githubusercontent.com/assets/1642635/12534396/cc742502-c257-11e5-86f1-763697debeab.png)

**Comment by vpklotar** [comment]
I would belive that a standardized CSS-Library for unified styling is prefer in a solution like this, it means pepole can write new pages and improvments without having to worry about styling.

**Comment by quidsup** [comment]
I would rather minimise use Javascript and keep with HTML5 and adaptive CSS3 where possible.
I tried out your preview and it took quite a while to display the page. With a couple of different devices in Chrome / Firefox it was about 3-4 secs to load the blocklist.

I know my styling is absolute basic at the moment with the blocklists, but I would like to see it with that sort of view in a table. That could be done server side in PHP.

**Comment by mariogrip** [comment]
May I ask why you would minimize Javascript? 

I'm aware about the delay, that should be fixed that in my latest version.

The reason why I use JavaScript is to take away the load from there server and make much more dynamic webpages. Nearly everything happens clients side now. This also should be mobile friendly.

btw, I just pushed a new version with stats and upgrade, it only missing the "filter function" at stats and the front page to have the same functions as the original.

**Comment by quidsup** [comment]
I admit my opinion is a few years old and was based more around accommodating users who have noscript or do cross site blocking.

I've read a few articles today and I see there is more of a mixture with Google in particular doing more client side, but then I saw Facebook and Twitter doing more server side.

I need to consider that the web interface is not dealing with a huge volume of users, but it is dealing with a reasonable size volume of data, certainly more so in future when the blocklist could go well over 100K sites, and historical look back of DNS data could be dealing with anything from 1MB to say 100MB worth of log data, which will need to be presented to the user in a clear concise format.

The capabilities of the server can be considered to be as low as a RPi B model 1.

The historical look back wasn't as taxing as I feared on a RPi B model 2 because I changed how the archiving is done on the log files and ripped out 90% of info from dnsmasq log that isn't needed.
Speed could be improved slightly more, but it wasn't different from reading three weeks worth of logs compared to how long it takes to read the daily log file.

I'll take a look soon
