### ISSUE TITLE
Does it work single-pc?

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#66]
I just switched to Kubuntu as my Main OS, i don't want to re-set this up on my NAS because it caused issues with lag and requiring the pc 24/7, if i install this on my pc, will it work for the pc? (PC in terms of my main computer)

**Comment by Serkan-devel** [comment]
It would work. You just need tweak things with dnsmasq https://www.youtube.com/watch?v=a5dUJ0SlGP0 (if it works) is accessable by typing http://localhost/ in your browser. The thing is thou you might need to have it running 24/7 if you want other devices to join. It might make problems finding devices on your network with this configuration but if it is 24/7 on and is the default dns set on your router, It would work fine. I think that it would be slower than an adblocker due to it being it always in the background but it block more than that.

Go for it.

**Comment by ShayBox** [comment]
Thanks :D
