### ISSUE TITLE
Change port?

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#69]
I moved my admin and sink folder to /var/notrack/(files here) and it works, and changed Lighttpd port to 81, because I have Apache on port 80. When i visit a website that's blocked it tries to go to port 80 still, what file would i change to fix that?

Possible future addition, custom port on installation if lighttpd is not already installed (no existing site) or use a virtual host (separate config) so that it runs on a separate port than the default lighttpd config.
Example: https://redmine.lighttpd.net/projects/1/wiki/docs_modsimplevhost

**Comment by quidsup** [comment]
You can't.
Browsers automatically default to port 80 or 443 (depending whether HTTP or HTTPS).
DNS lookups are not able to point the browser to a different port.

Your options are:
1. Change sink hole page to a different server
In /etc/notrack/notrack.conf
IPVersion = 127.0.0.1
(Which will divert away from your Apache server, but will cause a delay to your internet browsing because it will be accessing a server with doesn't exist)

2. Host everything on your Apache server.
The back end scripts don't interact with Lighttpd, so you can use any web server.

**Comment by ShayBox** [comment]
Ahh, i see. well i'll try putting it on apache, if that doesnt work then ill reverse the two ports

**Comment by Serkan-devel** [comment]
port 81 is a system port unoficially used for malware and onion-routing. You could use ports like 8080 and point your browser to <host>:8080
